name: tz-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.18=h382b9c6_0
  - aws-c-cal=0.6.11=hd34e5fa_0
  - aws-c-common=0.9.15=h93a5062_0
  - aws-c-compression=0.2.18=hd34e5fa_3
  - aws-c-event-stream=0.4.2=h247c08a_8
  - aws-c-http=0.8.1=hf9e830b_10
  - aws-c-io=0.14.7=h33d81b3_6
  - aws-c-mqtt=0.10.4=h5f4abda_0
  - aws-c-s3=0.5.7=h7644b7e_2
  - aws-c-sdkutils=0.1.15=hd34e5fa_3
  - aws-checksums=0.1.18=hd34e5fa_3
  - aws-crt-cpp=0.26.8=h7541583_2
  - aws-sdk-cpp=1.11.267=h18943f6_7
  - azure-core-cpp=1.11.1=he231e37_1
  - azure-identity-cpp=1.6.0=hd1853d3_1
  - azure-storage-blobs-cpp=12.10.0=h2ffa867_1
  - azure-storage-common-cpp=12.5.0=h09a5875_4
  - blosc=1.21.5=h9c252e8_1
  - bottleneck=1.3.8=py311h9ea6feb_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - c-blosc2=2.14.4=ha57e6be_1
  - ca-certificates=2024.7.4=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hd1e100b_0
  - cartopy=0.23.0=py311hfbe21a1_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cfitsio=4.4.0=h808cd33_1
  - cftime=1.6.3=py311h9ea6feb_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311hcc98501_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py311h92babd0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=hebf3989_0
  - fiona=1.9.6=py311h1c26527_0
  - fmt=10.2.1=h2ffa867_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py311h05b510d_0
  - freetype=2.12.1=hadb7bae_2
  - freexl=2.0.0=hfbad9fb_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gdal=3.8.5=py311h7f90d8e_2
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.12.1=h965bd2d_0
  - geotiff=1.7.1=h6e650f3_16
  - giflib=5.2.2=h93a5062_0
  - h5netcdf=1.3.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py311hd41bb03_102
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=nompi_h751145d_101
  - icu=73.2=hc8870d7_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - json-c=0.17=h40ed0f5_0
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - kealib=1.5.3=h210d843_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_hebf3989_0
  - libaec=1.1.3=hebf3989_0
  - libarchive=3.7.2=hcacb583_1
  - libblas=3.9.0=22_osxarm64_openblas
  - libboost-headers=1.84.0=hce30654_2
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.8.5=h2f7ae65_2
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.80.0=hfc324ee_6
  - libgoogle-cloud=2.23.0=hbebe991_1
  - libgoogle-cloud-storage=2.23.0=h8a76758_1
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libintl=0.22.5=h8fbad5d_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libkml=1.3.0=h1eb4d9f_1018
  - liblapack=3.9.0=22_osxarm64_openblas
  - libnetcdf=4.9.2=nompi_h291a7c2_113
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libpng=1.6.43=h091b4b1_0
  - libpq=16.2=h0f8b458_1
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - librttopo=1.1.0=hc8f776e_15
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.1.0=h77c30ab_5
  - libsqlite=3.45.3=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=h07db509_3
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.6=h0d0cfa8_2
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=18.1.3=hcd81f8e_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h93a5062_1001
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h05b510d_0
  - matplotlib=3.8.4=py311ha1ab1f8_0
  - matplotlib-base=3.8.4=py311hb58f1d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - minizip=4.0.5=hc35e051_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.6.5=nompi_py311ha6bebe6_100
  - networkx=3.3=pyhd8ed1ab_1
  - nspr=4.35=hb7217d7_0
  - nss=3.98=h5ce2875_0
  - numexpr=2.10.0=py311h4b4568b_0
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.2=h9f1df11_0
  - openpyxl=3.1.4=py311h1fc4b72_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py311hfbe21a1_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h26f9a81_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py311h0b5d0a1_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=hebf3989_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - plotly=5.22.0=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - polars=1.1.0=py311h769438f_0
  - poppler=24.04.0=h42742f0_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.2=hf829917_1
  - proj=9.4.0=h52fb9d0_1
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyomo=6.6.1=py311ha891d26_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py311ha70c146_6
  - pypsa=0.28.0=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.9.2=py311hf4904c8_2
  - pytest=8.3.2=pyhd8ed1ab_0
  - python=3.11.9=h932a869_0_cpython
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=26.0.2=py311h93cf3d9_0
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rpds-py=0.18.1=py311h98c6a39_0
  - rtree=1.2.0=py311hd698ff7_0
  - scikit-learn=1.4.2=py311h696fe38_0
  - scipy=1.13.0=py311h4f9446f_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=69.5.1=pyhd8ed1ab_0
  - shapely=2.0.4=py311h0815064_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hd04f947_1
  - spdlog=1.13.0=h5fcca99_0
  - sqlite=3.45.3=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py311h5d790af_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.22.0=hf0716ca_3
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py311h05b510d_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzcode=2024a=h93a5062_0
  - tzdata=2024a=h0c530f3_0
  - uriparser=0.9.7=h13dd4ca_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - validators=0.28.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xerces-c=3.2.5=hf393695_0
  - xlsxwriter=3.1.9=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hebf3989_1
  - zlib=1.2.13=h53f4e23_5
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - annotated-types==0.6.0
      - bayesian-optimization==1.5.0
      - calmap==0.0.11
      - dask==2024.4.2
      - gurobipy==10.0.0
      - highspy==1.7.1.dev1
      - kaleido==0.2.1
      - linopy==0.4.3
      - orjson==3.10.1
      - partd==1.4.1
      - platypus==1.0
      - platypus-opt==1.2.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydantic-settings==2.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - tqdm==4.66.2
      - tz-osemosys==0.0.14.dev2+ge80e24f
      - tza-pypsa==0.0.1
      - xarray==2024.3.0
      - zipp==3.18.1
